name: Update GitHub Secrets

on:
  push:
    branches:
      - main  # Trigger only on push to the main branch
    paths:
      - ".env"  # Trigger only if the .env file changes

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.G_TOKEN }}" | gh auth login --with-token

      # Extract and update secrets
      - name: Update GitHub Secrets
        run: |
          # Ensure the .env file exists
          if [ ! -f .env ]; then
            echo "No .env file found. Skipping..."
            exit 0
          fi

          # Read the .env file
          while IFS= read -r line; do
            # Ignore comments and empty lines
            if [[ "$line" == \#* || -z "$line" ]]; then
              continue
            fi

            # Split the line into key and value
            IFS='=' read -r key value <<< "$line"

            # Add/update the secret in GitHub
            echo "Updating secret: $key"
            echo "$value" | gh secret set "$key" --repo "${{ github.repository }}" --body -
          done < .env
